#pragma once
#define ASSET_DEFAULT_PATH TEXT("Assets\\")

#define ASSET_DEFAULT_SCENE_PATH TEXT("Assets\\Scenes\\")
#define ASSET_DEFAULT_STATICMESH_PATH TEXT("Assets\\Meshes\\")
#define ASSET_DEFAULT_TEXTURE_PATH TEXT("Assets\\Textures\\")
#define ASSET_DEFAULT_MATERIAL_PATH TEXT("Assets\\Materials\\")

#define ASSET_DEFAULT_SCENE_EXTENSION TEXT(".tscene")
#define ASSET_DEFAULT_STATICMESH_EXTENSION TEXT(".tsmesh")
#define ASSET_DEFAULT_MATERIAL_EXTENSION TEXT(".tmat")